sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.5
env:
  - RAILS_VERSION=4.2.11
  - RAILS_VERSION=5.0.7
  - RAILS_VERSION=5.1.7
  - RAILS_VERSION=5.2.3
before_install:
    - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
    - gem install bundler -v '< 2'
script: bundle exec rspec
